using MediatR;
using Wordix.Application.Common.Constants;
using Wordix.Application.Common.Interfaces.Persistence;
using Wordix.Application.Features.Imports.Dtos.Responses;
using Wordix.Application.Features.Imports.Mappers;
using Wordix.Application.Features.Lookups.Models;
using Wordix.Application.Features.Lookups.Services;
using Wordix.Domain.Entities;
using Wordix.Domain.Enums;

namespace Wordix.Application.Features.Imports.Commands.TestProviderPhraseCreation;

/// <summary>
/// Provider-created phrase oluşturma test handler'ıdır.
/// 
/// Bu handler:
/// - Dil kodlarını Language tablosundan çözer.
/// - ProviderPhraseCreationService'i çağırır.
/// - Sonucu response DTO'ya map eder.
/// </summary>
public sealed class TestProviderPhraseCreationCommandHandler
    : IRequestHandler<TestProviderPhraseCreationCommand, TestProviderPhraseCreationResponse>
{
    private readonly IRepository<Language> _languageRepository;
    private readonly IProviderPhraseCreationService _providerPhraseCreationService;

    public TestProviderPhraseCreationCommandHandler(
        IRepository<Language> languageRepository,
        IProviderPhraseCreationService providerPhraseCreationService)
    {
        _languageRepository = languageRepository;
        _providerPhraseCreationService = providerPhraseCreationService;
    }

    /// <summary>
    /// Provider-created phrase test akışını yürütür.
    /// </summary>
    public async Task<TestProviderPhraseCreationResponse> Handle(
        TestProviderPhraseCreationCommand request,
        CancellationToken cancellationToken)
    {
        var sourceLanguageCode = NormalizeLanguageCode(request.SourceLanguageCode);
        var targetLanguageCode = NormalizeLanguageCode(request.TargetLanguageCode);
        var normalizedText = NormalizeText(request.Text);

        var sourceLanguage = await _languageRepository.FirstOrDefaultAsync(
            language => language.Code == sourceLanguageCode && language.IsActive,
            cancellationToken);

        if (sourceLanguage is null)
        {
            var failureResult = ProviderPhraseCreationResult.Failure(
                normalizedText,
                $"Kaynak dil bulunamadı veya aktif değil. Code: {sourceLanguageCode}");

            return TestProviderPhraseCreationMapper.ToResponse(failureResult);
        }

        var targetLanguage = await _languageRepository.FirstOrDefaultAsync(
            language => language.Code == targetLanguageCode && language.IsActive,
            cancellationToken);

        if (targetLanguage is null)
        {
            var failureResult = ProviderPhraseCreationResult.Failure(
                normalizedText,
                $"Hedef dil bulunamadı veya aktif değil. Code: {targetLanguageCode}");

            return TestProviderPhraseCreationMapper.ToResponse(failureResult);
        }

        var creationRequest = new ProviderPhraseCreationRequest
        {
            Text = request.Text,
            NormalizedText = normalizedText,
            MeaningText = request.MeaningText,
            SourceLanguageId = sourceLanguage.Id,
            TargetLanguageId = targetLanguage.Id,

            // Azure runtime fallback phrase türünü güvenilir biçimde bilmez.
            // Bu yüzden Unknown bırakıyoruz.
            PhraseType = PhraseType.Unknown,

            // Runtime lookup sonucunda oluşacak içerik olduğu için UserLookup.
            SourceType = LearningItemSourceType.UserLookup,

            // Gerçek veri kaynağı Azure Translator.
            ContentSource = ContentSource.AzureTranslator,
            QualityStatus = ContentQualityStatus.AutoGenerated,
            SourceProvider = ImportConstants.ProviderNames.AzureTranslator,

            ShortDefinition = null,
            PartOfSpeech = null,
            Category = "provider-phrase-test",
            ExternalSourceKey = null
        };

        var creationResult = await _providerPhraseCreationService.CreateAsync(
            creationRequest,
            cancellationToken);

        return TestProviderPhraseCreationMapper.ToResponse(creationResult);
    }

    /// <summary>
    /// Dil kodunu normalize eder.
    /// </summary>
    private static string NormalizeLanguageCode(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().ToLowerInvariant();
    }

    /// <summary>
    /// Phrase metnini normalize eder.
    /// </summary>
    private static string NormalizeText(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().ToLowerInvariant();
    }
}