services:
  wordix-keycloak-db:
    image: postgres:17-alpine
    container_name: wordix-keycloak-db
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - wordix_keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wordix-network

  wordix-keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: wordix-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: wordix-keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      wordix-keycloak-db:
        condition: service_healthy
    networks:
      - wordix-network

  wordix-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wordix-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - wordix_mssql_data:/var/opt/mssql
    networks:
      - wordix-network

  wordix-api:
    container_name: wordix-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__WordixDb: "Server=wordix-mssql,1433;Database=WordixDb;User Id=sa;Password=Kartal1453.;TrustServerCertificate=True;Encrypt=False"

      Authentication__Keycloak__Authority: "http://host.docker.internal:8080/realms/wordix"
      Authentication__Keycloak__Audience: "wordix-api"
      Authentication__Keycloak__RequireHttpsMetadata: "false"
    depends_on:
      - wordix-mssql
      - wordix-keycloak
    networks:
      - wordix-network

volumes:
  wordix_keycloak_db_data:
  wordix_mssql_data:

networks:
  wordix-network:
    driver: bridge