// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wordix.Persistence.Contexts;

#nullable disable

namespace Wordix.Persistence.Migrations
{
    [DbContext(typeof(WordixDbContext))]
    [Migration("20260702115558_AddUserLearningNotesAndFlags")]
    partial class AddUserLearningNotesAndFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wordix.Domain.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeycloakUserId");

                    b.HasIndex("KeycloakUserId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.DeckItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserLearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserLearningItemId");

                    b.HasIndex("DeckId", "UserLearningItemId")
                        .IsUnique();

                    b.ToTable("DeckItems", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "en",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "English",
                            NativeName = "English"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "tr",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Turkish",
                            NativeName = "Türkçe"
                        });
                });

            modelBuilder.Entity("Wordix.Domain.Entities.LearningItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CefrLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyGroup")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyGroup");

                    b.HasIndex("IsActive");

                    b.HasIndex("LanguageId", "ItemType");

                    b.ToTable("LearningItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CefrLevel = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyGroup = 2,
                            IsActive = true,
                            ItemType = 1,
                            LanguageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SourceType = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CefrLevel = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyGroup = 1,
                            IsActive = true,
                            ItemType = 1,
                            LanguageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SourceType = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CefrLevel = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyGroup = 2,
                            IsActive = true,
                            ItemType = 1,
                            LanguageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SourceType = 1
                        });
                });

            modelBuilder.Entity("Wordix.Domain.Entities.LearningProgressHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewConfidenceScore")
                        .HasColumnType("int");

                    b.Property<int>("NewLearningStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldConfidenceScore")
                        .HasColumnType("int");

                    b.Property<int>("OldLearningStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserLearningProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserLearningProgressId", "CreatedAt");

                    b.ToTable("LearningProgressHistories", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.LookupHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedQueryText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ProviderType")
                        .HasColumnType("int");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasCreatedFromProvider")
                        .HasColumnType("bit");

                    b.Property<bool>("WasFoundInDatabase")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InputType");

                    b.HasIndex("KeycloakUserId");

                    b.HasIndex("LearningItemId");

                    b.HasIndex("NormalizedQueryText");

                    b.HasIndex("ProviderType");

                    b.HasIndex("SourceLanguageId");

                    b.HasIndex("TargetLanguageId");

                    b.ToTable("LookupHistories", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Meaning", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeaningText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortDefinition")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("LearningItemId", "TargetLanguageId", "DisplayOrder");

                    b.HasIndex("LearningItemId", "TargetLanguageId", "IsPrimary");

                    b.ToTable("Meanings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            Category = "general",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPrimary = true,
                            LearningItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            MeaningText = "başarmak",
                            PartOfSpeech = "verb",
                            ShortDefinition = "Bir hedefe ulaşmak veya istenen sonucu elde etmek.",
                            TargetLanguageId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            Category = "general",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPrimary = true,
                            LearningItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            MeaningText = "mükemmel",
                            PartOfSpeech = "adjective",
                            ShortDefinition = "Eksiksiz, kusursuz veya çok iyi olan.",
                            TargetLanguageId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            Category = "general",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsPrimary = true,
                            LearningItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            MeaningText = "geliştirmek",
                            PartOfSpeech = "verb",
                            ShortDefinition = "Bir şeyi daha iyi hale getirmek.",
                            TargetLanguageId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PhraseType")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId")
                        .IsUnique();

                    b.HasIndex("NormalizedText");

                    b.HasIndex("PhraseType");

                    b.ToTable("Phrases", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AddedToDictionaryBecauseWrong")
                        .HasColumnType("bit");

                    b.Property<int>("AnswerResult")
                        .HasColumnType("int");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("QuizQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResponseTimeMilliseconds")
                        .HasColumnType("int");

                    b.Property<Guid?>("SelectedQuizOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAnswer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerResult");

                    b.HasIndex("KeycloakUserId");

                    b.HasIndex("QuizQuestionId");

                    b.HasIndex("SelectedQuizOptionId");

                    b.HasIndex("KeycloakUserId", "AnsweredAt");

                    b.ToTable("QuizAnswers", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuizQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("QuizQuestionId", "IsCorrect");

                    b.ToTable("QuizOptions", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsSystemRecommended")
                        .HasColumnType("bit");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId");

                    b.HasIndex("QuizSessionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("QuizQuestions", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DifficultyGroup")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeSystemRecommendations")
                        .HasColumnType("bit");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("QuizContentMode")
                        .HasColumnType("int");

                    b.Property<int>("QuizSourceType")
                        .HasColumnType("int");

                    b.Property<int>("QuizType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId");

                    b.HasIndex("Status");

                    b.HasIndex("KeycloakUserId", "StartedAt");

                    b.ToTable("QuizSessions", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Sentence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalSentenceId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("License")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSentenceId");

                    b.HasIndex("LearningItemId")
                        .IsUnique()
                        .HasFilter("[LearningItemId] IS NOT NULL");

                    b.HasIndex("SourceProvider");

                    b.HasIndex("LanguageId", "NormalizedText")
                        .IsUnique();

                    b.ToTable("Sentences", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.SentenceTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("License")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedTranslatedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SourceSentenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("SourceProvider");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("SourceSentenceId", "TargetLanguageId");

                    b.HasIndex("SourceSentenceId", "TargetLanguageId", "NormalizedTranslatedText")
                        .IsUnique();

                    b.ToTable("SentenceTranslations", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlagType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserLearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserLearningItemId");

                    b.HasIndex("UserLearningItemId", "FlagType")
                        .IsUnique();

                    b.ToTable("UserLearningFlags", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SelectedMeaningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceLookupHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId");

                    b.HasIndex("SelectedMeaningId");

                    b.HasIndex("SourceLookupHistoryId");

                    b.HasIndex("KeycloakUserId", "IsActive");

                    b.HasIndex("KeycloakUserId", "LearningItemId")
                        .IsUnique();

                    b.ToTable("UserLearningItems", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserLearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserLearningItemId");

                    b.ToTable("UserLearningNotes", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsecutiveCorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveWrongCount")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LearningConfidenceScore")
                        .HasColumnType("int");

                    b.Property<int>("LearningStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepetitionLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserLearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearningStatus");

                    b.HasIndex("NextReviewDate");

                    b.HasIndex("UserLearningItemId")
                        .IsUnique();

                    b.ToTable("UserLearningProgresses", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDifficultyGroup")
                        .HasColumnType("int");

                    b.Property<int>("DefaultQuizType")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeSystemRecommendations")
                        .HasColumnType("bit");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("MotivationMessagesEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("PreferredQuestionCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId")
                        .IsUnique();

                    b.HasIndex("NormalizedText");

                    b.ToTable("Words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LearningItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            NormalizedText = "achieve",
                            PartOfSpeech = "verb",
                            Text = "achieve"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LearningItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            NormalizedText = "perfect",
                            PartOfSpeech = "adjective",
                            Text = "perfect"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LearningItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            NormalizedText = "improve",
                            PartOfSpeech = "verb",
                            Text = "improve"
                        });
                });

            modelBuilder.Entity("Wordix.Domain.Entities.DeckItem", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.Deck", null)
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.UserLearningItem", null)
                        .WithMany()
                        .HasForeignKey("UserLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.LearningItem", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.LearningProgressHistory", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.UserLearningProgress", null)
                        .WithMany()
                        .HasForeignKey("UserLearningProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.LookupHistory", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wordix.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Meaning", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Phrase", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithOne()
                        .HasForeignKey("Wordix.Domain.Entities.Phrase", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizAnswer", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.QuizQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.QuizOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedQuizOptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizOption", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.QuizQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.QuizSession", null)
                        .WithMany()
                        .HasForeignKey("QuizSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Sentence", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithOne()
                        .HasForeignKey("Wordix.Domain.Entities.Sentence", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.SentenceTranslation", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.Sentence", null)
                        .WithMany()
                        .HasForeignKey("SourceSentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningFlag", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.UserLearningItem", null)
                        .WithMany()
                        .HasForeignKey("UserLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningItem", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wordix.Domain.Entities.Meaning", null)
                        .WithMany()
                        .HasForeignKey("SelectedMeaningId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wordix.Domain.Entities.LookupHistory", null)
                        .WithMany()
                        .HasForeignKey("SourceLookupHistoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningNote", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.UserLearningItem", null)
                        .WithMany()
                        .HasForeignKey("UserLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.UserLearningProgress", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.UserLearningItem", null)
                        .WithOne()
                        .HasForeignKey("Wordix.Domain.Entities.UserLearningProgress", "UserLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wordix.Domain.Entities.Word", b =>
                {
                    b.HasOne("Wordix.Domain.Entities.LearningItem", null)
                        .WithOne()
                        .HasForeignKey("Wordix.Domain.Entities.Word", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
