using Wordix.Application.Common.Constants;
using Wordix.Domain.Enums;

namespace Wordix.Application.Features.Lookups.Models;

/// <summary>
/// Provider'dan gelen phrase çeviri sonucunu global catalog'a kaydetmek için kullanılan request modelidir.
/// 
/// Bu model ne zaman kullanılacak?
/// - Kullanıcı "give up" gibi bir phrase arar.
/// - Local database'de phrase bulunamaz.
/// - Azure Translator'dan "vazgeçmek" gibi bir sonuç gelir.
/// - Bu sonuç LearningItem + Phrase + Meaning olarak global catalog'a kaydedilir.
/// 
/// Bu işlem kullanıcı dictionary'sine kayıt değildir.
/// Kullanıcı isterse daha sonra bu LearningItem'ı kendi dictionary'sine ayrıca kaydeder.
/// </summary>
public sealed record ProviderPhraseCreationRequest
{
    /// <summary>
    /// Kullanıcının aradığı veya provider'a gönderilen phrase metnidir.
    /// 
    /// Örnek:
    /// give up
    /// look after
    /// by the way
    /// </summary>
    public string Text { get; init; } = string.Empty;

    /// <summary>
    /// Phrase'in normalize edilmiş halidir.
    /// 
    /// Boş gelirse service Text üzerinden normalize eder.
    /// </summary>
    public string? NormalizedText { get; init; }

    /// <summary>
    /// Provider'dan gelen Türkçe anlam/çeviri metnidir.
    /// 
    /// Örnek:
    /// vazgeçmek
    /// ilgilenmek
    /// bu arada
    /// </summary>
    public string MeaningText { get; init; } = string.Empty;

    /// <summary>
    /// Phrase'in kaynak dil id'sidir.
    /// 
    /// İngilizce phrase için English language Id verilir.
    /// </summary>
    public Guid SourceLanguageId { get; init; }

    /// <summary>
    /// Meaning'in hedef dil id'sidir.
    /// 
    /// Türkçe meaning için Turkish language Id verilir.
    /// </summary>
    public Guid TargetLanguageId { get; init; }

    /// <summary>
    /// Phrase türüdür.
    /// 
    /// Azure bize "bu phrasal verbdir" gibi güvenilir tür bilgisi vermez.
    /// Bu yüzden runtime Azure fallback için default Unknown kullanacağız.
    /// </summary>
    public PhraseType PhraseType { get; init; } = PhraseType.Unknown;

    /// <summary>
    /// Bu içeriğin sisteme hangi akışla eklendiğini belirtir.
    /// 
    /// Runtime lookup sonucunda oluşacağı için default UserLookup kullanıyoruz.
    /// Gerçek kaynak ise ContentSource ile AzureTranslator olarak tutulur.
    /// </summary>
    public LearningItemSourceType SourceType { get; init; } = LearningItemSourceType.UserLookup;

    /// <summary>
    /// İçeriğin gerçek veri kaynağıdır.
    /// 
    /// Bu service ilk aşamada Azure Translator sonucu için kullanılacak.
    /// </summary>
    public ContentSource ContentSource { get; init; } = ContentSource.AzureTranslator;

    /// <summary>
    /// İçeriğin kalite/güven durumudur.
    /// 
    /// Azure çevirisi insan doğrulamasından geçmediği için AutoGenerated kabul ediyoruz.
    /// </summary>
    public ContentQualityStatus QualityStatus { get; init; } = ContentQualityStatus.AutoGenerated;

    /// <summary>
    /// Provider adı.
    /// 
    /// Meaning.SourceProvider alanına yazılır.
    /// </summary>
    public string SourceProvider { get; init; } = ImportConstants.ProviderNames.AzureTranslator;

    /// <summary>
    /// Opsiyonel kısa açıklama.
    /// Azure runtime fallback için genellikle boş kalır.
    /// </summary>
    public string? ShortDefinition { get; init; }

    /// <summary>
    /// Opsiyonel part of speech bilgisi.
    /// Azure runtime fallback için genellikle boş kalır.
    /// </summary>
    public string? PartOfSpeech { get; init; }

    /// <summary>
    /// Opsiyonel kategori bilgisi.
    /// İleride "provider-lookup" gibi değerler verilebilir.
    /// </summary>
    public string? Category { get; init; }

    /// <summary>
    /// Dış kaynak takip anahtarıdır.
    /// Boş gelirse service güvenli bir key üretir.
    /// </summary>
    public string? ExternalSourceKey { get; init; }
}