using Wordix.Domain.Enums;

namespace Wordix.Application.Common.Models.Translation;

/// <summary>
/// Azure Translator gibi dış çeviri provider'larından dönen standart sonucu temsil eder.
/// 
/// Bu model neden var?
/// - Azure response formatını doğrudan handler veya lookup service içine taşımak istemiyoruz.
/// - Application katmanı sadece başarılı/başarısız çeviri sonucunu bilmelidir.
/// - Provider değişse bile üst katmanların kullandığı result modeli değişmemelidir.
/// </summary>
public sealed record TranslationResult
{
    /// <summary>
    /// Provider isteği başarılı şekilde işledi mi?
    /// </summary>
    public bool Succeeded { get; init; }

    /// <summary>
    /// Çevrilmek istenen kaynak metindir.
    /// </summary>
    public string SourceText { get; init; } = string.Empty;

    /// <summary>
    /// Provider'dan dönen çevrilmiş metindir.
    /// </summary>
    public string TranslatedText { get; init; } = string.Empty;

    /// <summary>
    /// Çevrilmiş metnin normalize edilmiş halidir.
    /// 
    /// Duplicate kontrolünde veya Meaning karşılaştırmasında kullanılabilir.
    /// </summary>
    public string NormalizedTranslatedText { get; init; } = string.Empty;

    /// <summary>
    /// Kaynak dil kodudur.
    /// </summary>
    public string SourceLanguageCode { get; init; } = string.Empty;

    /// <summary>
    /// Hedef dil kodudur.
    /// </summary>
    public string TargetLanguageCode { get; init; } = string.Empty;

    /// <summary>
    /// Sonucu üreten gerçek içerik kaynağıdır.
    /// 
    /// Bu fazda sadece AzureTranslator kullanacağız.
    /// </summary>
    public ContentSource ContentSource { get; init; } = ContentSource.AzureTranslator;

    /// <summary>
    /// Provider adı string olarak tutulur.
    /// 
    /// Örnek:
    /// AzureTranslator
    /// </summary>
    public string SourceProvider { get; init; } = string.Empty;

    /// <summary>
    /// İçeriğin kalite durumudur.
    /// 
    /// Azure çevirisi insan tarafından doğrulanmadığı için
    /// default olarak AutoGenerated kabul edilir.
    /// </summary>
    public ContentQualityStatus QualityStatus { get; init; } = ContentQualityStatus.AutoGenerated;

    /// <summary>
    /// Provider'ın işlediği karakter sayısıdır.
    /// 
    /// İleride maliyet, limit ve analytics için kullanılabilir.
    /// </summary>
    public int CharacterCount { get; init; }

    /// <summary>
    /// Provider başarısız olduysa hata mesajıdır.
    /// </summary>
    public string? ErrorMessage { get; init; }

    /// <summary>
    /// Başarılı translation result üretir.
    /// </summary>
    public static TranslationResult Success(
        string sourceText,
        string translatedText,
        string sourceLanguageCode,
        string targetLanguageCode,
        ContentSource contentSource,
        string sourceProvider,
        ContentQualityStatus qualityStatus = ContentQualityStatus.AutoGenerated)
    {
        return new TranslationResult
        {
            Succeeded = true,
            SourceText = sourceText,
            TranslatedText = translatedText,
            NormalizedTranslatedText = NormalizeText(translatedText),
            SourceLanguageCode = NormalizeLanguageCode(sourceLanguageCode),
            TargetLanguageCode = NormalizeLanguageCode(targetLanguageCode),
            ContentSource = contentSource,
            SourceProvider = sourceProvider,
            QualityStatus = qualityStatus,
            CharacterCount = sourceText.Length,
            ErrorMessage = null
        };
    }

    /// <summary>
    /// Başarısız translation result üretir.
    /// </summary>
    public static TranslationResult Failure(
        string sourceText,
        string sourceLanguageCode,
        string targetLanguageCode,
        ContentSource contentSource,
        string sourceProvider,
        string errorMessage)
    {
        return new TranslationResult
        {
            Succeeded = false,
            SourceText = sourceText,
            TranslatedText = string.Empty,
            NormalizedTranslatedText = string.Empty,
            SourceLanguageCode = NormalizeLanguageCode(sourceLanguageCode),
            TargetLanguageCode = NormalizeLanguageCode(targetLanguageCode),
            ContentSource = contentSource,
            SourceProvider = sourceProvider,
            QualityStatus = ContentQualityStatus.NeedsReview,
            CharacterCount = sourceText.Length,
            ErrorMessage = errorMessage
        };
    }

    /// <summary>
    /// Dil kodunu normalize eder.
    /// </summary>
    private static string NormalizeLanguageCode(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().ToLowerInvariant();
    }

    /// <summary>
    /// Çeviri metnini duplicate kontrolü için normalize eder.
    /// </summary>
    private static string NormalizeText(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().ToLowerInvariant();
    }
}