using Wordix.Domain.Enums;

namespace Wordix.Application.Common.Models.Import;

/// <summary>
/// Example sentence enrichment service'ine gönderilen request modelidir.
/// 
/// Bu model neyi temsil eder?
/// - Parser'dan gelen Tatoeba cümle çiftleri.
/// - Hangi LearningItem tipleriyle eşleşme yapılacağı.
/// - Hangi content source'lardan gelen Word/Phrase itemların zenginleştirileceği.
/// - DryRun modunda mı çalışılacağı.
/// - Batch/limit ayarları.
/// 
/// Bu model entity değildir.
/// Application service akışında veri taşımak için kullanılır.
/// </summary>
public sealed record ExampleSentenceEnrichmentRequest
{
    /// <summary>
    /// Parser'dan gelen example sentence satırlarıdır.
    /// 
    /// Örnek:
    /// SourceText = "I have to go to sleep."
    /// TranslatedText = "Yatmaya gitmek zorundayım."
    /// </summary>
    public IReadOnlyCollection<ExampleSentenceImportRow> Rows { get; init; }
        = Array.Empty<ExampleSentenceImportRow>();

    /// <summary>
    /// Kaynak dil kodudur.
    /// 
    /// Örnek:
    /// en
    /// 
    /// Bu kod repository tarafında mevcut Word/Phrase LearningItem adaylarını filtrelemek için kullanılır.
    /// </summary>
    public string SourceLanguageCode { get; init; } = string.Empty;

    /// <summary>
    /// Hedef dil kodudur.
    /// 
    /// Örnek:
    /// tr
    /// 
    /// Bu kod SentenceTranslation için hedef Language kaydını bulmakta kullanılacak.
    /// </summary>
    public string TargetLanguageCode { get; init; } = string.Empty;

    /// <summary>
    /// Hangi LearningItem tiplerine örnek cümle bağlanabileceğini belirtir.
    /// 
    /// İlk production kuralımız:
    /// - Word
    /// - Phrase
    /// 
    /// Sentence itemları için bu ilişki normalde kullanılmaz.
    /// Çünkü Sentence zaten kendi başına cümledir.
    /// </summary>
    public IReadOnlyCollection<LearningItemType> AllowedItemTypes { get; init; }
        = new[]
        {
            LearningItemType.Word,
            LearningItemType.Phrase
        };

    /// <summary>
    /// Hangi ContentSource'lardan gelen Word/Phrase itemların zenginleştirileceğini belirtir.
    /// 
    /// Neden gerekli?
    /// - Tatoeba enrichment genelde verified/imported sistem havuzunu zenginleştirmek içindir.
    /// - Azure fallback ile kullanıcı lookup'undan gelen AutoGenerated içerikleri
    ///   otomatik enrichment havuzuna almak istemeyebiliriz.
    /// 
    /// Bu liste boş gelirse service güvenli default uygulayacaktır.
    /// </summary>
    public IReadOnlyCollection<ContentSource> AllowedContentSources { get; init; }
        = Array.Empty<ContentSource>();

    /// <summary>
    /// True ise database'e kayıt atılmaz.
    /// Sadece kaç kayıt oluşturulabileceği hesaplanır.
    /// 
    /// Import/enrichment akışlarında dry-run çok önemlidir.
    /// Büyük veri üzerinde gerçek insert öncesi sonucu görmemizi sağlar.
    /// </summary>
    public bool DryRun { get; init; } = true;

    /// <summary>
    /// Tek bir LearningItem için en fazla kaç example sentence bağlanacağını belirtir.
    /// 
    /// Örnek:
    /// abandon kelimesi Tatoeba'da 50 cümlede geçebilir.
    /// Ama ilk aşamada 3 örnek cümle yeterli olabilir.
    /// </summary>
    public int MaxExamplesPerLearningItem { get; init; } = 3;

    /// <summary>
    /// Toplamda en fazla kaç yeni example sentence bağlantısı oluşturulacağını belirtir.
    /// 
    /// Büyük dosyalarda DB'yi bir anda şişirmemek için kullanılır.
    /// </summary>
    public int? MaxCreatedItems { get; init; }

    /// <summary>
    /// Response'a en fazla kaç mesaj alınacağını belirtir.
    /// </summary>
    public int MaxMessages { get; init; } = 100;

    /// <summary>
    /// Response'a en fazla kaç created/would-create sample item alınacağını belirtir.
    /// </summary>
    public int SampleSize { get; init; } = 20;
}