using Wordix.Domain.Enums;

namespace Wordix.Application.Common.Models.Import;

/// <summary>
/// ExternalContentCache oluşturmak veya güncellemek için kullanılan Application modelidir.
/// 
/// Bu model neden var?
/// - ExternalContentCache entity constructor'ı provider/cache metadata bilgisi ister.
/// - Azure, Tatoeba, Kaikki gibi farklı provider akışları aynı standart request modeliyle cache yazabilir.
/// - Service tarafında uzun parametre listesi kullanmak yerine okunabilir bir model sağlar.
/// 
/// Bu model entity değildir.
/// Sadece cache set/refresh operasyonu için kullanılan request modelidir.
/// </summary>
public sealed record ExternalContentCacheSetRequest
{
    /// <summary>
    /// Provider türüdür.
    /// 
    /// Örnek:
    /// Translation, Dictionary, ExampleSentence, Import.
    /// </summary>
    public ProviderType ProviderType { get; init; }

    /// <summary>
    /// Provider adıdır.
    /// 
    /// Örnek:
    /// AzureTranslator, Tatoeba, WiktionaryKaikki.
    /// </summary>
    public string ProviderName { get; init; } = string.Empty;

    /// <summary>
    /// Provider üzerinde yapılan operasyon adıdır.
    /// 
    /// Örnek:
    /// Translate
    /// ParseTatoebaExampleSentences
    /// EnrichKaikkiMeanings
    /// </summary>
    public string OperationName { get; init; } = string.Empty;

    /// <summary>
    /// Cache lookup için kullanılan teknik anahtardır.
    /// 
    /// Örnek:
    /// azure:translate:en:tr:microservice
    /// azure:translate:en:tr:take responsibility
    /// </summary>
    public string CacheKey { get; init; } = string.Empty;

    /// <summary>
    /// Cache'e yazılacak JSON payload değeridir.
    /// 
    /// Dikkat:
    /// Buraya secret, token, API key, authorization header veya connection string yazılmamalıdır.
    /// Sadece tekrar kullanılabilir provider sonucu yazılmalıdır.
    /// </summary>
    public string CachedPayloadJson { get; init; } = string.Empty;

    /// <summary>
    /// Cache kaydına konu olan normalize input değeridir.
    /// 
    /// Örnek:
    /// microservice
    /// take responsibility
    /// </summary>
    public string? NormalizedInput { get; init; }

    /// <summary>
    /// Kaynak dil kodudur.
    /// 
    /// Örnek:
    /// en
    /// </summary>
    public string? SourceLanguageCode { get; init; }

    /// <summary>
    /// Hedef dil kodudur.
    /// 
    /// Örnek:
    /// tr
    /// </summary>
    public string? TargetLanguageCode { get; init; }

    /// <summary>
    /// Cache içeriğinin gerçek veri kaynağıdır.
    /// 
    /// Örnek:
    /// AzureTranslator, Tatoeba, WiktionaryKaikki.
    /// </summary>
    public ContentSource ContentSource { get; init; } = ContentSource.Unknown;

    /// <summary>
    /// Cache içeriğinin kalite/güven durumudur.
    /// 
    /// Örnek:
    /// Azure çevirisi AutoGenerated,
    /// Tatoeba cümlesi Imported olabilir.
    /// </summary>
    public ContentQualityStatus QualityStatus { get; init; } = ContentQualityStatus.Unknown;

    /// <summary>
    /// Cache kaydının geçerlilik bitiş zamanıdır.
    /// 
    /// Null ise süre bazlı expiration uygulanmayabilir.
    /// </summary>
    public DateTime? ExpiresAtUtc { get; init; }
}