using Wordix.Application.Common.Constants;
using Wordix.Application.Common.Interfaces.Translation;
using Wordix.Application.Common.Models.Translation;
using Wordix.Application.Features.Lookups.Models;
using Wordix.Application.Features.Lookups.Services;
using Wordix.Domain.Enums;

namespace Wordix.Infrastructure.Dictionary;

/// <summary>
/// Lookup fallback için Azure Translator tabanlı DictionaryProvider adapter'ıdır.
/// 
/// Bu class ne yapar?
/// - CreateLookupCommandHandler hâlâ IDictionaryProvider abstraction'ını kullanır.
/// - Bu adapter içeride ITranslationProvider üzerinden Azure Translator çağırır.
/// - Word/Phrase için DictionaryProviderMeaning döner.
/// - Sentence için DictionaryProviderSentenceTranslation döner.
/// 
/// Neden doğrudan handler içinde ITranslationProvider çağırmıyoruz?
/// - Handler dış provider detayını bilmesin.
/// - Lookup use-case'i provider abstraction ile çalışmaya devam etsin.
/// - Yarın Azure yerine farklı provider gelirse handler değişmeden kalabilsin.
/// </summary>
public sealed class AzureTranslationDictionaryProvider : IDictionaryProvider
{
    private const string ProviderName = ImportConstants.ProviderNames.AzureTranslator;

    private readonly ITranslationProvider _translationProvider;
    private readonly ILookupClassifier _lookupClassifier;

    public AzureTranslationDictionaryProvider(
        ITranslationProvider translationProvider,
        ILookupClassifier lookupClassifier)
    {
        _translationProvider = translationProvider;
        _lookupClassifier = lookupClassifier;
    }

    /// <summary>
    /// DB'de bulunmayan lookup input'u için Azure Translator fallback çağrısı yapar.
    /// </summary>
    public async Task<DictionaryProviderResult> FindAsync(
        string normalizedText,
        string sourceLanguageCode,
        string targetLanguageCode,
        CancellationToken cancellationToken = default)
    {
        var safeText = NormalizeText(normalizedText);
        var sourceCode = NormalizeLanguageCode(sourceLanguageCode);
        var targetCode = NormalizeLanguageCode(targetLanguageCode);

        if (string.IsNullOrWhiteSpace(safeText) ||
            string.IsNullOrWhiteSpace(sourceCode) ||
            string.IsNullOrWhiteSpace(targetCode))
        {
            return CreateNotFoundResult(
                safeText,
                sourceCode,
                targetCode);
        }

        var inputType = _lookupClassifier.Classify(safeText);

        var translationResult = await _translationProvider.TranslateAsync(
            new TranslationRequest
            {
                Text = safeText,
                SourceLanguageCode = sourceCode,
                TargetLanguageCode = targetCode,
                Purpose = "lookup-azure-fallback",
                Context = $"Wordix lookup fallback for {inputType} input."
            },
            cancellationToken);

        if (!translationResult.Succeeded ||
            string.IsNullOrWhiteSpace(translationResult.TranslatedText))
        {
            return CreateNotFoundResult(
                safeText,
                sourceCode,
                targetCode);
        }

        var translatedText = translationResult.TranslatedText.Trim();

        if (inputType is LookupInputType.Sentence)
        {
            return DictionaryProviderResult.SentenceFoundResult(
                normalizedText: safeText,
                sourceLanguageCode: sourceCode,
                targetLanguageCode: targetCode,
                providerName: ProviderName,
                sentenceTranslations: new[]
                {
                    new DictionaryProviderSentenceTranslation
                    {
                        TranslatedText = translatedText,
                        SourceProvider = ProviderName,
                        License = null
                    }
                },
                providerType: ProviderType.Translation,
                contentSource: ContentSource.AzureTranslator,
                qualityStatus: ContentQualityStatus.AutoGenerated);
        }

        return DictionaryProviderResult.FoundResult(
            normalizedText: safeText,
            sourceLanguageCode: sourceCode,
            targetLanguageCode: targetCode,
            providerName: ProviderName,
            meanings: new[]
            {
                new DictionaryProviderMeaning
                {
                    Translation = translatedText,
                    Definition = null,
                    ExampleSentence = null,
                    PartOfSpeech = null
                }
            },
            providerType: ProviderType.Translation,
            contentSource: ContentSource.AzureTranslator,
            qualityStatus: ContentQualityStatus.AutoGenerated);
    }

    /// <summary>
    /// Azure fallback başarısız olduğunda standart not-found result üretir.
    /// </summary>
    private static DictionaryProviderResult CreateNotFoundResult(
        string normalizedText,
        string sourceLanguageCode,
        string targetLanguageCode)
    {
        return DictionaryProviderResult.NotFound(
            normalizedText: normalizedText,
            sourceLanguageCode: sourceLanguageCode,
            targetLanguageCode: targetLanguageCode,
            providerName: ProviderName,
            providerType: ProviderType.Translation,
            contentSource: ContentSource.AzureTranslator,
            qualityStatus: ContentQualityStatus.AutoGenerated);
    }

    /// <summary>
    /// Lookup text değerini güvenli hale getirir.
    /// </summary>
    private static string NormalizeText(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().ToLowerInvariant();
    }

    /// <summary>
    /// Dil kodunu normalize eder.
    /// </summary>
    private static string NormalizeLanguageCode(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : value.Trim().ToLowerInvariant();
    }
}