namespace Wordix.Application.Features.Imports.Dtos.Responses;

/// <summary>
/// Azure Translator smoke test response modelidir.
/// 
/// Bu response database'e yazılan bir şeyi temsil etmez.
/// Sadece Azure provider sonucunu API'de okunabilir hale getirir.
/// </summary>
public sealed record TestAzureTranslationResponse
{
    /// <summary>
    /// Azure provider isteği başarılı mı?
    /// </summary>
    public bool Succeeded { get; init; }

    /// <summary>
    /// Çevrilmek istenen kaynak metin.
    /// </summary>
    public string SourceText { get; init; } = string.Empty;

    /// <summary>
    /// Azure'dan dönen çevrilmiş metin.
    /// </summary>
    public string TranslatedText { get; init; } = string.Empty;

    /// <summary>
    /// Normalize edilmiş çeviri metni.
    /// </summary>
    public string NormalizedTranslatedText { get; init; } = string.Empty;

    /// <summary>
    /// Kaynak dil kodu.
    /// </summary>
    public string SourceLanguageCode { get; init; } = string.Empty;

    /// <summary>
    /// Hedef dil kodu.
    /// </summary>
    public string TargetLanguageCode { get; init; } = string.Empty;

    /// <summary>
    /// İçeriğin hangi provider'dan geldiğini string olarak gösterir.
    /// Örnek: AzureTranslator.
    /// </summary>
    public string ContentSource { get; init; } = string.Empty;

    /// <summary>
    /// Kalite durumunu string olarak gösterir.
    /// Örnek: AutoGenerated.
    /// </summary>
    public string QualityStatus { get; init; } = string.Empty;

    /// <summary>
    /// Provider adı.
    /// </summary>
    public string SourceProvider { get; init; } = string.Empty;

    /// <summary>
    /// İşlenen karakter sayısı.
    /// </summary>
    public int CharacterCount { get; init; }

    /// <summary>
    /// Provider başarısızsa hata mesajı.
    /// </summary>
    public string? ErrorMessage { get; init; }
}