namespace Wordix.Domain.Enums;

/// <summary>
/// Bir içerik parçasının kalite/güven durumunu temsil eder.
/// 
/// Bu enum neden gerekli?
/// Import işleminin başarılı olması, verinin doğru olduğu anlamına gelmez.
/// Örneğin LibreTranslate düzgün cevap dönmüş olabilir ama tek kelime anlamı bağlamdan dolayı hatalı olabilir.
/// 
/// Bu yüzden import status ile content quality status ayrı tutulur.
/// </summary>
public enum ContentQualityStatus
{
    /// <summary>
    /// Kalite durumu bilinmiyor veya henüz belirlenmemiş.
    /// </summary>
    Unknown = 0,

    /// <summary>
    /// Veri manuel olarak doğrulandı veya çok güvenilir bir kaynak üzerinden onaylandı.
    /// </summary>
    Verified = 1,

    /// <summary>
    /// Veri dış kaynaktan import edildi.
    /// Kullanılabilir ama manuel doğrulama yapılmamış olabilir.
    /// 
    /// Örnek:
    /// - Kaikki/Wiktionary'den gelen anlam
    /// - Tatoeba'dan gelen örnek cümle
    /// </summary>
    Imported = 2,

    /// <summary>
    /// Veri otomatik provider tarafından üretildi.
    /// 
    /// Örnek:
    /// - LibreTranslate ile çevrilmiş anlam
    /// - LibreTranslate ile çevrilmiş cümle
    /// </summary>
    AutoGenerated = 3,

    /// <summary>
    /// Veri eksik, şüpheli veya fallback olarak üretildi.
    /// Admin/review kontrolü gerektirir.
    /// </summary>
    NeedsReview = 4,

    /// <summary>
    /// Veri review sonucunda reddedildi.
    /// Normal kullanıcı akışında gösterilmemelidir.
    /// </summary>
    Rejected = 5
}